import Head from "next/head";
import div from "next/link";

import { api } from "@/utils/api";

export default function Home() {
  const authMutation = api.loral.auth.useMutation();

  const authClickHandler = () => {
    authMutation.mutate(undefined, {
      onSuccess: (data) => {
        if (data.redirect_uri) {
          window.location.href = data.redirect_uri;
          return;
        }
        if (data.token) {
          alert(`Already authenticated. Access token printed to console.`);
          console.log("Access Token: ", data.token);
          return;
        }
      },
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Demo <span className="text-[hsl(280,100%,70%)]">Loral</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <div
              className="flex max-w-xs cursor-pointer flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={() => authClickHandler()}
            >
              <h3 className="text-2xl font-bold">Auth to Loral →</h3>
              <div className="text-lg">
                Securely authenticated access to dozens of APIs.
              </div>
            </div>
            <div className="flex max-w-xs cursor-pointer flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </div>
          </div>
          {/* <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
        </div>
      </main>
    </>
  );
}
